// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// DisProgrCov_Gibbs
List DisProgrCov_Gibbs(List MCMC_input);
RcppExport SEXP _SUMS_DisProgrCov_Gibbs(SEXP MCMC_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type MCMC_input(MCMC_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(DisProgrCov_Gibbs(MCMC_input));
    return rcpp_result_gen;
END_RCPP
}
// DisProgrGibbs_DP
List DisProgrGibbs_DP(List MCMC_input);
RcppExport SEXP _SUMS_DisProgrGibbs_DP(SEXP MCMC_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type MCMC_input(MCMC_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(DisProgrGibbs_DP(MCMC_input));
    return rcpp_result_gen;
END_RCPP
}
// DisProgrGibbs_DP_dH0
List DisProgrGibbs_DP_dH0(List MCMC_input);
RcppExport SEXP _SUMS_DisProgrGibbs_DP_dH0(SEXP MCMC_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type MCMC_input(MCMC_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(DisProgrGibbs_DP_dH0(MCMC_input));
    return rcpp_result_gen;
END_RCPP
}
// DisProgrGibbs_Mix
List DisProgrGibbs_Mix(List MCMC_input);
RcppExport SEXP _SUMS_DisProgrGibbs_Mix(SEXP MCMC_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type MCMC_input(MCMC_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(DisProgrGibbs_Mix(MCMC_input));
    return rcpp_result_gen;
END_RCPP
}
// DisProgrGibbs_Mix_dH0
List DisProgrGibbs_Mix_dH0(List MCMC_input);
RcppExport SEXP _SUMS_DisProgrGibbs_Mix_dH0(SEXP MCMC_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type MCMC_input(MCMC_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(DisProgrGibbs_Mix_dH0(MCMC_input));
    return rcpp_result_gen;
END_RCPP
}
// DisProgrGibbs_Param
List DisProgrGibbs_Param(List MCMC_input);
RcppExport SEXP _SUMS_DisProgrGibbs_Param(SEXP MCMC_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type MCMC_input(MCMC_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(DisProgrGibbs_Param(MCMC_input));
    return rcpp_result_gen;
END_RCPP
}
// DisProgrGibbs_Param_dH0
List DisProgrGibbs_Param_dH0(List MCMC_input);
RcppExport SEXP _SUMS_DisProgrGibbs_Param_dH0(SEXP MCMC_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type MCMC_input(MCMC_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(DisProgrGibbs_Param_dH0(MCMC_input));
    return rcpp_result_gen;
END_RCPP
}
// expmat_Tesch1
arma::mat expmat_Tesch1(const arma::mat& a);
RcppExport SEXP _SUMS_expmat_Tesch1(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(expmat_Tesch1(a));
    return rcpp_result_gen;
END_RCPP
}
// log_dmvnrm_arma
double log_dmvnrm_arma(arma::rowvec x, arma::rowvec mu, arma::mat Omega);
RcppExport SEXP _SUMS_log_dmvnrm_arma(SEXP xSEXP, SEXP muSEXP, SEXP OmegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Omega(OmegaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_dmvnrm_arma(x, mu, Omega));
    return rcpp_result_gen;
END_RCPP
}
// rgwish_c
arma::mat rgwish_c(double nu, arma::mat Ti, arma::mat G, double threshold);
RcppExport SEXP _SUMS_rgwish_c(SEXP nuSEXP, SEXP TiSEXP, SEXP GSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ti(TiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type G(GSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(rgwish_c(nu, Ti, G, threshold));
    return rcpp_result_gen;
END_RCPP
}
// rwish
arma::mat rwish(double nu, arma::mat Psi);
RcppExport SEXP _SUMS_rwish(SEXP nuSEXP, SEXP PsiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Psi(PsiSEXP);
    rcpp_result_gen = Rcpp::wrap(rwish(nu, Psi));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SUMS_DisProgrCov_Gibbs", (DL_FUNC) &_SUMS_DisProgrCov_Gibbs, 1},
    {"_SUMS_DisProgrGibbs_DP", (DL_FUNC) &_SUMS_DisProgrGibbs_DP, 1},
    {"_SUMS_DisProgrGibbs_DP_dH0", (DL_FUNC) &_SUMS_DisProgrGibbs_DP_dH0, 1},
    {"_SUMS_DisProgrGibbs_Mix", (DL_FUNC) &_SUMS_DisProgrGibbs_Mix, 1},
    {"_SUMS_DisProgrGibbs_Mix_dH0", (DL_FUNC) &_SUMS_DisProgrGibbs_Mix_dH0, 1},
    {"_SUMS_DisProgrGibbs_Param", (DL_FUNC) &_SUMS_DisProgrGibbs_Param, 1},
    {"_SUMS_DisProgrGibbs_Param_dH0", (DL_FUNC) &_SUMS_DisProgrGibbs_Param_dH0, 1},
    {"_SUMS_expmat_Tesch1", (DL_FUNC) &_SUMS_expmat_Tesch1, 1},
    {"_SUMS_log_dmvnrm_arma", (DL_FUNC) &_SUMS_log_dmvnrm_arma, 3},
    {"_SUMS_rgwish_c", (DL_FUNC) &_SUMS_rgwish_c, 4},
    {"_SUMS_rwish", (DL_FUNC) &_SUMS_rwish, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_SUMS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
